"use client"
import React from "react";
import { Provider } from "react-redux";
import { store } from "./redux/store/reduxStore";

import localFont from 'next/font/local'
 
// Font files can be colocated inside of `pages`
const myFont = localFont({ src: '../public/fonts/Inter/Inter-VariableFont_slnt,wght.ttf' })

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>

      <body className={myFont.className}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
